server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/board-db # DB 주소
    username: root # DB 계정
    password: password # DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
